if Code.ensure_loaded?(Igniter) do
  defmodule Mix.Tasks.NbTs.Install do
    @moduledoc """
    Installs and configures NbTs for TypeScript type generation.

    Should be run with `mix igniter.install nb_ts`

    ## Usage

        mix igniter.install nb_ts [options]

    ## Options

      * `--output-dir` - Directory for generated TypeScript types (default: "assets/js/types")
      * `--yes` - Skip confirmation prompts

    ## Examples

        # Basic installation
        mix igniter.install nb_ts

        # Custom output directory
        mix igniter.install nb_ts --output-dir lib/my_app_web/assets/types

        # Quick install without prompts
        mix igniter.install nb_ts --yes

    ## What it does

    This installer will:

      1. Add `nb_ts` dependency to mix.exs (if running standalone)
      2. Configure TypeScript output directory in config/config.exs
      3. Create output directory with .gitkeep file
      4. Update tsconfig.json to include generated types (if exists)
      5. Add `mix ts.gen` alias for convenient type generation
      6. Run initial type generation to create base types
      7. Print helpful next steps for getting started

    ## Integration with Other Packages

    NbTs integrates with:
    - **NbSerializer**: Generates TypeScript interfaces from serializer schemas
    - **NbInertia**: Generates TypeScript interfaces from Inertia page props

    ## Post-Installation

    After installation:

    1. Review generated types in your configured output directory
    2. Run `mix ts.gen` after modifying serializers or Inertia pages
    3. Import types in your TypeScript/JavaScript files

    For more information, see: https://hexdocs.pm/nb_ts
    """

    @shortdoc "Installs NbTs for TypeScript type generation"

    use Igniter.Mix.Task

    @impl Igniter.Mix.Task
    def info(_argv, _source) do
      %Igniter.Mix.Task.Info{
        group: :nb,
        example: "mix igniter.install nb_ts --output-dir assets/js/types",
        composes: ["deps.get"],
        schema: [
          output_dir: :string,
          yes: :boolean
        ],
        aliases: [
          o: :output_dir,
          y: :yes
        ],
        defaults: [
          output_dir: "assets/js/types",
          yes: false
        ]
      }
    end

    @impl Igniter.Mix.Task
    def igniter(igniter) do
      output_dir = igniter.args.options[:output_dir] || "assets/js/types"
      skip_prompts = igniter.args.options[:yes] || false

      igniter
      |> Igniter.Project.Formatter.import_dep(:nb_ts)
      |> print_welcome_message(skip_prompts)
      |> configure_output_directory(output_dir)
      |> create_output_directory(output_dir)
      |> maybe_update_tsconfig(output_dir)
      |> add_type_generation_alias()
      |> add_initial_type_generation_task(output_dir)
      |> print_next_steps(output_dir)
    end

    defp print_welcome_message(igniter, skip_prompts) do
      unless skip_prompts do
        Mix.shell().info("""

        ╔═══════════════════════════════════════════════════════════════╗
        ║                                                               ║
        ║              Welcome to NbTs Installer                        ║
        ║                                                               ║
        ║   TypeScript Type Generation for Elixir                      ║
        ║                                                               ║
        ╚═══════════════════════════════════════════════════════════════╝

        This installer will set up NbTs in your project with:
          - TypeScript type generation from serializers
          - Inertia page prop type generation
          - Compile-time type validation
          - Mix alias for convenient type generation

        """)
      end

      igniter
    end

    defp configure_output_directory(igniter, output_dir) do
      igniter
      |> Igniter.Project.Config.configure(
        "config.exs",
        :nb_ts,
        [:output_dir],
        output_dir
      )
      |> Igniter.add_notice("""
      Configured NbTs output directory: #{output_dir}

      Generated TypeScript types will be written to this directory.
      """)
    end

    defp create_output_directory(igniter, output_dir) do
      # Create a .gitkeep file to ensure the directory exists
      gitkeep_path = Path.join(output_dir, ".gitkeep")

      igniter
      |> Igniter.create_new_file(gitkeep_path, "# TypeScript types generated by nb_ts\n",
        on_exists: :skip
      )
      |> Igniter.add_notice("""
      Created output directory: #{output_dir}

      This directory will contain generated TypeScript types.
      """)
    end

    defp maybe_update_tsconfig(igniter, output_dir) do
      tsconfig_path = "assets/tsconfig.json"

      if File.exists?(tsconfig_path) do
        update_tsconfig(igniter, tsconfig_path, output_dir)
      else
        igniter
        |> Igniter.add_notice("""
        No tsconfig.json found at #{tsconfig_path}

        If you're using TypeScript, make sure to include the generated types directory
        in your tsconfig.json:

        {
          "compilerOptions": {
            "baseUrl": ".",
            "paths": {
              "@/types/*": ["./#{output_dir}/*"]
            }
          },
          "include": [
            "#{output_dir}/**/*"
          ]
        }
        """)
      end
    end

    defp update_tsconfig(igniter, tsconfig_path, output_dir) do
      igniter
      |> Igniter.update_file(tsconfig_path, fn source ->
        content = Rewrite.Source.get(source, :content)

        case Jason.decode(content) do
          {:ok, json} ->
            # Add the types directory to the include array
            updated_json =
              json
              |> update_in(["include"], fn
                nil ->
                  ["#{output_dir}/**/*"]

                includes when is_list(includes) ->
                  if "#{output_dir}/**/*" in includes do
                    includes
                  else
                    includes ++ ["#{output_dir}/**/*"]
                  end
              end)
              |> update_in(["compilerOptions", "paths"], fn
                nil ->
                  %{"@/types/*" => ["./#{output_dir}/*"]}

                paths when is_map(paths) ->
                  if Map.has_key?(paths, "@/types/*") do
                    paths
                  else
                    Map.put(paths, "@/types/*", ["./#{output_dir}/*"])
                  end
              end)

            case Jason.encode(updated_json, pretty: true) do
              {:ok, new_content} ->
                Rewrite.Source.update(source, :content, fn _ -> new_content <> "\n" end)

              _ ->
                source
            end

          _ ->
            source
        end
      end)
      |> Igniter.add_notice("""
      Updated tsconfig.json to include generated types directory.

      The types will be available at @/types/* in your TypeScript imports.
      """)
    end

    defp add_type_generation_alias(igniter) do
      igniter
      |> Igniter.Project.TaskAliases.add_alias("ts.gen", ["nb_ts.gen.types"])
      |> Igniter.add_notice("""
      Added mix alias: mix ts.gen

      You can now run 'mix ts.gen' instead of 'mix nb_ts.gen.types'
      """)
    end

    defp add_initial_type_generation_task(igniter, output_dir) do
      # Add a task to run after installation to generate initial types
      igniter
      |> Igniter.add_task("nb_ts.gen.types", [
        "--output-dir",
        output_dir
      ])
      |> Igniter.add_notice("""
      Will generate initial TypeScript types after installation completes.
      """)
    end

    defp print_next_steps(igniter, output_dir) do
      Igniter.add_notice(igniter, """

      ╔═══════════════════════════════════════════════════════════════╗
      ║                                                               ║
      ║           NbTs Installation Complete!                         ║
      ║                                                               ║
      ╚═══════════════════════════════════════════════════════════════╝

      Installation Summary:
          ✓ NbTs core library
          ✓ Output directory configured: #{output_dir}
          ✓ Mix alias added: mix ts.gen
          ✓ Initial types will be generated

      Next Steps:

      1. Review generated types in #{output_dir}/

      2. Use the generated types in your TypeScript code:

         import type { User } from '@/types/serializers';
         import type { UsersIndexProps } from '@/types/inertia';

         export default function UsersIndex({ users }: UsersIndexProps) {
           // Fully typed!
         }

      3. Regenerate types after changes:

         mix ts.gen
         # or
         mix nb_ts.gen.types

      4. For NbSerializer integration, define serializers with type annotations:

         defmodule MyApp.Serializers.UserSerializer do
           use NbSerializer.Serializer

           schema do
             field :id, :number
             field :name, :string
             field :email, :string
           end
         end

      5. For NbInertia integration, define page props:

         inertia_page :users_index do
           prop :users, [UserSerializer]
           prop :total, :number
         end

      Documentation & Resources:

        • NbTs Docs: https://hexdocs.pm/nb_ts
        • GitHub: https://github.com/nordbeam/nb_ts
        • NbSerializer: https://hexdocs.pm/nb_serializer
        • NbInertia: https://hexdocs.pm/nb_inertia

      Happy typing! 🎯
      """)
    end
  end
else
  # Fallback when Igniter is not available
  defmodule Mix.Tasks.NbTs.Install do
    @moduledoc "Installs NbTs. Should be run with `mix igniter.install nb_ts`"
    @shortdoc @moduledoc

    use Mix.Task

    def run(_argv) do
      Mix.shell().error("""
      The task 'nb_ts.install' requires igniter to be run.

      Please install igniter and try again.

      For more information, see: https://hexdocs.pm/igniter
      """)

      exit({:shutdown, 1})
    end
  end
end
