/**
 * Module augmentation for @inertiajs/react to support RouteResult from nb_routes.
 *
 * This file adds support for passing route helper results (objects with url and method)
 * directly to Inertia's Link component and router methods.
 *
 * Generated by nb_ts - do not edit manually.
 */

/**
 * Route result object returned by nb_routes helpers in rich mode.
 *
 * Example:
 *   const route = user_path(1);  // { url: "/users/1", method: "get" }
 *   <Link href={route}>User</Link>
 */
export type RouteResult = {
  url: string;
  method: 'get' | 'post' | 'put' | 'patch' | 'delete' | 'head';
};

/**
 * Type alias for href values that can be either a string URL or a RouteResult.
 *
 * Example:
 *   const href1: Href = "/users/1";
 *   const href2: Href = user_path(1);
 */
export type Href = string | RouteResult;

declare module '@inertiajs/react' {
  import type { RouteResult } from './inertia';

  /**
   * Augment InertiaLinkProps to accept RouteResult in href.
   */
  interface InertiaLinkProps {
    href: string | RouteResult;
  }

  /**
   * Augment Router interface to accept RouteResult in visit and related methods.
   */
  interface Router {
    visit(href: string | RouteResult, options?: VisitOptions): void;
    get(href: string | RouteResult, data?: object, options?: VisitOptions): void;
    post(href: string | RouteResult, data?: object, options?: VisitOptions): void;
    put(href: string | RouteResult, data?: object, options?: VisitOptions): void;
    patch(href: string | RouteResult, data?: object, options?: VisitOptions): void;
    delete(href: string | RouteResult, options?: VisitOptions): void;
    reload(options?: VisitOptions): void;
  }
}
