/**
 * Modal type definitions for NbInertia modal and slideover support.
 *
 * These types match the Elixir NbInertia.Modal module and provide type safety
 * for modal configuration when using render_inertia_modal.
 *
 * Generated by nb_ts - do not edit manually.
 */

/**
 * Modal size presets and custom sizes
 */
export type ModalSize = 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl' | '4xl' | '5xl' | 'full' | string;

/**
 * Modal position presets and custom positions
 */
export type ModalPosition = 'center' | 'top' | 'bottom' | 'left' | 'right' | string;

/**
 * Configuration for a modal instance
 *
 * This interface defines all available configuration options for modals and slideovers.
 * All fields are optional with sensible defaults.
 *
 * Maps to the Elixir NbInertia.Modal.config() typespec.
 */
export interface ModalConfig {
  /**
   * Size of the modal
   * @default 'md'
   *
   * Presets: 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl' | '4xl' | '5xl' | 'full'
   * Custom: Any valid CSS class string (e.g., 'max-w-4xl')
   */
  size?: ModalSize;

  /**
   * Position of the modal on screen
   * @default 'center'
   *
   * Presets: 'center' | 'top' | 'bottom' | 'left' | 'right'
   * Custom: Any valid CSS class string
   */
  position?: ModalPosition;

  /**
   * Whether this is a slideover (slides in from side) instead of a modal
   * @default false
   */
  slideover?: boolean;

  /**
   * Show a close button in the top-right corner
   * @default true
   */
  closeButton?: boolean;

  /**
   * Require explicit close (disables ESC key and backdrop click)
   * @default false
   */
  closeExplicitly?: boolean;

  /**
   * Custom max-width CSS value
   * @example '800px', '50rem'
   */
  maxWidth?: string;

  /**
   * Custom padding classes for modal content
   * @default 'p-6'
   * @example 'p-8', 'px-4 py-6'
   */
  paddingClasses?: string;

  /**
   * Custom panel classes for the modal container
   * @default 'bg-white rounded-lg shadow-xl'
   * @example 'bg-gray-900 text-white rounded-xl'
   */
  panelClasses?: string;

  /**
   * Custom backdrop classes for the overlay
   * @default 'bg-black/50'
   * @example 'bg-gray-900/75', 'backdrop-blur-sm'
   */
  backdropClasses?: string;
}
